# Generated by Django 4.2.21 on 2025-06-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='size',
            field=models.IntegerField(blank=True, choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large'), (4, 'X-Large'), (5, 'XX-Large')], null=True),
        ),
    ]
